---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - run.terraform-operator.io
  resources:
  - terraforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - run.terraform-operator.io
  resources:
  - terraforms/finalizers
  verbs:
  - update
- apiGroups:
  - run.terraform-operator.io
  resources:
  - terraforms/status
  verbs:
  - get
  - patch
  - update
