apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-runner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: terraform-runner
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "update", "list"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "update", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-runner
subjects:
- kind: ServiceAccount
  name: terraform-runner # name of your service account
  namespace: default # this is the namespace your service account is in
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: terraform-runner
  apiGroup: rbac.authorization.k8s.io
