apiVersion: run.terraform-operator.io/v1alpha1
kind: Terraform
metadata:
  name: terraform-basic
spec:
  terraformVersion: 1.0.2

  module:
    source: git::ssh://git@github.com/IbraheemAlSaady/terraform-module-test.git
    # version: 0.0.2

  variables:
    - key: length
      value: "16"

  backend: |
    backend "local" {
      path = "/tmp/tfmodule/mytfstate.tfstate"
    }

  gitSSHKey:
    valueFrom:
      secret:
        secretName: git-ssh-key
        defaultMode: 0600

  # workspace: dev

  destroy: false
  deleteCompletedJobs: false

  retryLimit: 1

  outputs:
    - key: my_output
      moduleOutputName: result
