apiVersion: run.terraform-operator.io/v1alpha1
kind: Terraform
metadata:
  name: terraform-aws-s3
spec:
  terraformVersion: 1.0.2

  module:
    source: IbraheemAlSaady/test/module//modules/aws
    version: 0.0.2

  variables:
    - key: name
      value: "mytestrandombucket"
    - key: AWS_DEFAULT_REGION
      value: eu-west-1
      environmentVariable: true
    - key: AWS_ACCESS_KEY_ID
      environmentVariable: true
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_ACCESS_KEY_ID
    - key: AWS_SECRET_ACCESS_KEY
      environmentVariable: true
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_SECRET_ACCESS_KEY

  backend: |
    backend "s3" {
      bucket = "mybucket"
      key    = "path/to/my/key"
      region = "eu-west-1"
    }
  
  providersConfig: |
    terraform {
      required_providers {
        aws = {
          source  = "hashicorp/aws"
          version = "~> 3.0"
        }
      }
    }

    provider "aws" {
      region = "eu-west-1"
    }

  # workspace: dev

  destroy: false
  deleteCompletedJobs: false

  retryLimit: 1
  
  outputs:
    - key: bucket_id
      moduleOutputName: id 
