name: Pull Request

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make build

    ## Ref: https://github.com/golangci/golangci-lint-action
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3

    - name: Test
      run: make docker-build

    - name: Docker Build Test
      run: docker build -t controller:latest .
